// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface State {
    "running": boolean;
    "starting": boolean;
    "url"?: string;
    "startedAt": string;
    "error"?: string;
}
