// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as diagnostics$0 from "./internal/diagnostics/models.js";

export function InstallCodex(): $CancellablePromise<diagnostics$0.Snapshot> {
    return $Call.ByID(2252125960);
}

export function InstallNode(): $CancellablePromise<diagnostics$0.Snapshot> {
    return $Call.ByID(2048349969);
}

export function InstallProgress(): $CancellablePromise<string> {
    return $Call.ByID(962318050);
}

export function RefreshStatus(): $CancellablePromise<diagnostics$0.Snapshot> {
    return $Call.ByID(1963326979);
}

export function Status(): $CancellablePromise<diagnostics$0.Snapshot> {
    return $Call.ByID(838280468);
}
