// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Snapshot is the status shown by the desktop UI and local control API.
 */
export interface Snapshot {
    "platform": string;
    "architecture": string;
    "checkedAt": string;
    "node": ToolStatus;
    "codex": ToolStatus;
    "appServer": ToolStatus;
    "cloudflared": ToolStatus;
}

/**
 * ToolStatus describes one locally discoverable runtime or executable.
 */
export interface ToolStatus {
    "installed": boolean;
    "path"?: string;
    "version"?: string;
    "error"?: string;
}
