// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Device {
    "id": string;
    "name": string;
    "createdAt": string;
    "lastSeen": string;
    "connected"?: boolean;
    "threadCount": number;
}

export interface Pairing {
    "token": string;
    "expiresAt": string;
}
