// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface HeldThread {
    "id": string;
    "name": string;
    "status": string;
}

export interface State {
    "running": boolean;
    "starting": boolean;
    "stopping": boolean;
    "startedAt": string;
    "codexHome"?: string;
    "userAgent"?: string;
    "error"?: string;
}
